import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '../styles/globals.css'
import Icons from '@/components/helpers/icons'
import NavComponent from '@/components/navigation/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  Icons();
  return (
    <html className="p-0 m-0" lang="en">
      <body className={`p-0 m-0 ${inter.className}`}>
        <NavComponent/>
        {children}
      </body>
    </html>
  )
}
